export interface FormRequest {
  fullName: string
  warName: string
  registration: string
  birthDate: string
  rg: string
  cpf: string
  placeOfBirth: string
  ufNatural: string
  civilState: string
  cep: string
  address: string
  number: string
  city: string
  uf: string
  complement: string
  email: string
  cellphone: string
  phone: string
  gender: string
  motherName: string
  fatherName: string
  scolarity: string
  religion: string
  bloodType: string
  function: string
  actualSituation: string
  admissionDate: string
  role: string
  bodyOfLaw: string
  lotation: string
  workPost: string
}
