export const styles = {
  formContainer: {
    backgroundColor: "transparent",
    width: "100vw",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  formBox: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "white",
    width: "1313px",
    minHeight: "90vh",
    borderRadius: "16px",
  },
  columnFields: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  rowFields: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    backgroundColor: "transparent",
    height: "60px",
    width: "1200px",
  },
  dependentTitleRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "transparent",
    width: "1313px",
    height: "60px",
  },
  divider: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "black",
    width: "1110px",
    height: "1px",
    justifyContent: "center",
  },
  columnDependents: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  inputSize: {
    width: "300px",
  },
}
