export const styles = {
  formContainer: {
    backgroundColor: "transparent",
    width: "100vw",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  formBox: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "white",
    width: "1313px",
    minHeight: "90vh",
    borderRadius: "16px",
  },
  columnFields: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  rowFields: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "flex-start",
    backgroundColor: "transparent",
    maxWidth: "1200px",
    flexWrap: "wrap",
  },
  rowButtons: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginVertical: "30px",
  },
  dependentTitleRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  divider: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "black",
    width: "1200px",
    height: "1px",
    justifyContent: "center",
  },
  columnDependents: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  inputSize: {
    margin: "12px 8px 0px 0px",
  },
}
